"""init tables

Revision ID: 9645ac17bbe6
Revises: 
Create Date: 2020-09-30 14:13:00.399222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9645ac17bbe6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comp_name', sa.String(length=128), nullable=True),
    sa.Column('comp_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_comp_name'), 'comp', ['comp_name'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.String(length=15), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=True),
    sa.Column('player_gender', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_player_name'), 'player', ['player_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.create_table('entry',
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['comp_id'], ['comp.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('comp_id', 'player_id')
    )
    op.create_table('result',
    sa.Column('player_id', sa.String(length=15), nullable=False),
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=10), nullable=False),
    sa.Column('res1', sa.BigInteger(), nullable=True),
    sa.Column('res2', sa.BigInteger(), nullable=True),
    sa.Column('res3', sa.BigInteger(), nullable=True),
    sa.Column('res4', sa.BigInteger(), nullable=True),
    sa.Column('res5', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['comp_id'], ['comp.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'comp_id', 'round', 'item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('entry')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_player_player_name'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_comp_comp_name'), table_name='comp')
    op.drop_table('comp')
    # ### end Alembic commands ###
